# Generated by Django 3.2.4 on 2021-08-02 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=40, unique=True)),
                ('base_asset', models.CharField(max_length=20)),
                ('quote_asset', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Kline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=19)),
                ('high_price', models.DecimalField(decimal_places=8, max_digits=19)),
                ('low_price', models.DecimalField(decimal_places=8, max_digits=19)),
                ('close_price', models.DecimalField(decimal_places=8, max_digits=19)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=19)),
                ('quote_volume', models.DecimalField(decimal_places=8, max_digits=19)),
                ('taker_buy_base_volume', models.DecimalField(decimal_places=8, max_digits=19)),
                ('taker_buy_quote_volume', models.DecimalField(decimal_places=8, max_digits=19)),
                ('interval', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='klines.interval')),
                ('pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='klines.pair')),
            ],
        ),
    ]
